let name="Kelna", roll=101, maths=74, science=93, english=80, computer=95, social=78;
let total = maths + science + english + computer + social;
let average = total / 5;
let percentage=average;
let grade;
if(average >= 90) grade = "A";
else if(average >= 80) grade = "B";
else if(average >= 70) grade = "C";
else if(average >= 60) grade = "D";
else grade = "F";
console.log("STUDENT RESULT REPORT");
console.log("Name:", name);
console.log("Roll No:", roll);
console.log("Maths:", maths);
console.log("Science:", science);
console.log("English:", english);
console.log("Computer:", computer);
console.log("Social:", social);
console.log("Total:", total);
console.log("Average:", average);
console.log("Percentage", percentage+"%");
console.log("Grade:", grade);